### ISSUE TITLE
Quality Control Datasets

### ISSUE THREAD

**Issue by haitao-git** [stuckyb/gcdl#88]
**Quality Control Datasets**

[https://www.ncei.noaa.gov/access/crn/qcdatasets.html](https://www.ncei.noaa.gov/access/crn/qcdatasets.html)

datasets by weather stations, **not raster/gridded** 

2000-2022 monthly, daily, hourly, sub-hourly(5-minute) station data

variables:
air temperature, precipitation, global solar radiation, surface infrared temperature, relative humidity, soil moisture and temperature, wetness, and 1.5 meter wind speed

and some new products:

- Standardized Soil Moisture
- Soil Moisture Climatology
- Heat Exposure
- Drought Indices

**Comment by HeatherSavoy-USDA** [comment]
Since these are not gridded datasets, we do not intend on including them in GeoCDL.
